### ISSUE TITLE
Missing list of instructors for 2015-05-12-BUSM

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/amy#332] opened 2015-06-02 17:51 UTC
None of the instructors of https://chendaniely.github.io/2015-05-12-BUSM/ was listed at Amy.

@gvwilson I fixed that but I would like to know if the problem was due a bug on Amy or not.

**Comment by gvwilson** [comment] 2015-06-02 18:38
The bug is data input - I'm slowly catching up and entering things by 
comparing workshop web sites to Amy's contents.  If you'd like to help, 
you could figure out why the `reports` branch in my repo stopped working 
overnight when I merged django-countries - all of a sudden, `make 
all-activity` is producing a double stack trace when I run with the 
latest database.  (`make all-activity` runs the command I've built to 
dump all instructor activity, which we can then compare against what's 
archived in `config/workshops.yml` and `config/archived.yml`.)  
@pbanaszkiewicz, any idea what might have broken my reporting branch?

On 2015-06-02 1:51 PM, Raniere Silva wrote:
>
> None of the instructors of 
> https://chendaniely.github.io/2015-05-12-BUSM/ was listed at Amy.
>
> @gvwilson <https://github.com/gvwilson> I fixed that but I would like 
> to know if the problem was due a bug on Amy or not.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/swcarpentry/amy/issues/332>.
>

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Comment by wking** [comment] 2015-06-02 19:20
On Tue, Jun 02, 2015 at 11:38:22AM -0700, Greg Wilson wrote:
> … all of a sudden, `make all-activity` is producing a double stack
> trace when I run with the latest database…

It would be easier to figure out if you posted the stack traces, since
that might clarify the error without us needing to try and reproduce
it locally.

**Comment by gvwilson** [comment] 2015-06-02 20:33
1.  `git checkout master`
2.  `git pull upstream master` # to make sure I'm in sync
3.  `git checkout reports` # the branch where I'm building reporting tools
4.  `git merge master` # to make sure `reports` has everything
5.  `make test` # everything passes
6.  `make clean`
7.  `make database`
8.  `make migrations` # just in case
9.  `make all-activity` # runs `python3 manage.py 
report_all_instructor_activity` and produces a big blob of JSON
10. `scp swc:sites/amy.software-carpentry.org/db.sqlite3 ./db.sqlite3` # 
get the real database
11. `make migrations` # because schema changes
12. `make all-activity` # produces the stack trace shown below

Note: `make all-activity` with the production `db.sqlite3` worked fine 
on Sunday.

~~~
Traceback (most recent call last):
   File 
"/Users/gvwilson/anaconda/envs/py3k/lib/python3.3/site-packages/django/db/models/fields/related.py", 
line 585, in __get__
     rel_obj = getattr(instance, self.cache_name)
AttributeError: 'Task' object has no attribute '_event_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
   File "manage.py", line 10, in <module>
     execute_from_command_line(sys.argv)
   File 
"/Users/gvwilson/anaconda/envs/py3k/lib/python3.3/site-packages/django/core/management/__init__.py", 
line 338, in execute_from_command_line
     utility.execute()
   File 
"/Users/gvwilson/anaconda/envs/py3k/lib/python3.3/site-packages/django/core/management/__init__.py", 
line 330, in execute
     self.fetch_command(subcommand).run_from_argv(self.argv)
   File 
"/Users/gvwilson/anaconda/envs/py3k/lib/python3.3/site-packages/django/core/management/base.py", 
line 390, in run_from_argv
     self.execute(*args, **cmd_options)
   File 
"/Users/gvwilson/anaconda/envs/py3k/lib/python3.3/site-packages/django/core/management/base.py", 
line 441, in execute
     output = self.handle(*args, **options)
   File 
"/Users/gvwilson/s/amy/workshops/management/commands/report_all_instructor_activity.py", 
line 32, in handle
     for t in tasks]
   File 
"/Users/gvwilson/s/amy/workshops/management/commands/report_all_instructor_activity.py", 
line 32, in <listcomp>
     for t in tasks]
   File 
"/Users/gvwilson/anaconda/envs/py3k/lib/python3.3/site-packages/django/db/models/fields/related.py", 
line 602, in __get__
     rel_obj = qs.get()
   File 
"/Users/gvwilson/anaconda/envs/py3k/lib/python3.3/site-packages/django/db/models/query.py", 
line 334, in get
     self.model._meta.object_name
workshops.models.DoesNotExist: Event matching query does not exist.
make: *** [all-activity] Error 1
~~~

**Comment by wking** [comment] 2015-06-02 20:50
On Tue, Jun 02, 2015 at 01:33:28PM -0700, Greg Wilson wrote:
> 7.  `make database`
> 8.  `make migrations` # just in case
> 9.  `make all-activity` # runs `python3 manage.py 
> report_all_instructor_activity` and produces a big blob of JSON
> 10. `scp swc:sites/amy.software-carpentry.org/db.sqlite3 ./db.sqlite3` # 
> get the real database
> 11. `make migrations` # because schema changes
> 12. `make all-activity` # produces the stack trace shown below

If it works with the dummy database but not the live data, I suspect
the all-activity script assumes some constraint that's not enforced
by the database, and either:

* Data breaking that assumption has landed in the
  live database since the last time it was dumped into the saved
  database, or
* One of the migrations was broken, and it makes changes that break
  the unenforced assumption.

> "/Users/gvwilson/s/amy/workshops/management/commands/report_all_instructor_activity.py", 
> line 32, in handle
>      for t in tasks]
>    File 
> "/Users/gvwilson/s/amy/workshops/management/commands/report_all_instructor_activity.py", 
> line 32, in <listcomp>
>      for t in tasks]
>    File 

What is going on in this list comprehension?  Links to the source?

> workshops.models.DoesNotExist: Event matching query does not exist.

It sounds like your list comprehension in
report_all_instructor_activity is trying to find an Event associated
with a given task, but there are no such events in the database.  Can
you provide more information about the troublesome Task, it's
associated Events, and the query parameters you're using?

**Comment by pbanaszkiewicz** [comment] 2015-06-02 21:42
The error is: there's a task without existing event (probably assigned non-existing event). Not sure if we don't hit some Django bug here, too…

**Comment by gvwilson** [comment] 2015-06-02 21:43
Whoops - do you mean there's a database consistency violation?

On 2015-06-02 5:42 PM, Piotr Banaszkiewicz wrote:
>
> The error is: there's a task without existing event (probably assigned 
> non-existing event). Not sure if we don't hit some Django bug here, too…
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/swcarpentry/amy/issues/332#issuecomment-108107215>.
>

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Comment by pbanaszkiewicz** [comment] 2015-06-02 21:48
Yes, we have to delete tasks with IDs 11092, 11114, 11115, then the script doesn't bug out.

**Comment by wking** [comment] 2015-06-02 21:58
On Tue, Jun 02, 2015 at 02:48:42PM -0700, Piotr Banaszkiewicz wrote:
> Yes, we have to delete tasks with IDs 11092, 11114, 11115, then the
> script doesn't bug out.

Since we have such frequent logging, can we go back and see when these
tasks were added and look at the surrounding activity?  Access logs to
show which forms were being submitted around that time would be nice
too.

**Comment by pbanaszkiewicz** [comment] 2015-06-03 11:10
Last time I can see these events in the DB is from 2015-05-30 21:34:44 (my time).

Backup from -12h (for some reason I have two backups from that day) showed slight change in the notes for "2015-04-18-asu" (the missing event with ID 371; the admin noted invoice date). The other event, ID 381, the whole time had note "Whoops - this duplicates event 372.".

On 2015-05-31 I don't see these entries anymore.

In my emails I can see I reported to Greg:
```
DB backed_up, duplicated event 381 removed. Cheers!

On Sat, May 30, 2015 at 9:34 PM, Greg Wilson <
gvwilson@software-carpentry.org> wrote:

> ...is to manually erase (like really erase from the DB) the Event entry
> that's currently marked as 'deleted'.  Can you please back up the DB then
> do that and give me a shout and I'll try editing again?
> Thx,
> G
>
> --
> Dr. Greg Wilson    | gvwilson@software-carpentry.org
> Software Carpentry | http://software-carpentry.org
>
```

This doesn't, however, explain why event 371 went missing…

**Comment by gvwilson** [comment] 2015-06-03 12:06
Ouch - the most likely explanation is that I deleted Event 371 by hand.  
Can you please delete the tasks associated with it from the database and 
I promise never to do something like that again?

**Comment by pbanaszkiewicz** [comment] 2015-06-03 15:00
I'll bring back event 371 to the current production database and migrate tasks related to event 381 into event 372 if they're not there yet.

**Comment by gvwilson** [comment] 2015-06-03 15:09
Thanks - please let me know when it's done and I'll re-run my reporting.

On 2015-06-03 11:00 AM, Piotr Banaszkiewicz wrote:
>
> I'll bring back event 371 to the current production database and 
> migrate tasks related to event 381 into event 372 if they're not there 
> yet.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/swcarpentry/amy/issues/332#issuecomment-108471204>.
>

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Comment by pbanaszkiewicz** [comment] 2015-06-03 15:19
Okay, it should be OK now.

Here's what I've done:

1. moved one task (for person 3411) from event 371 to event 335
2. didn't touch event 335, although some details might be worth preserving from event 371 (reg key, attendance, first contact date)
3. removed all tasks that pointed at missing events 371, 382.

Cheers,
Piotr

**Comment by gvwilson** [comment] 2015-06-03 15:53
`make all-activity` in my `reports` branch is now running - thanks very 
much.  (And I promise never to manually edit the database again.)

On 2015-06-03 11:19 AM, Piotr Banaszkiewicz wrote:
>
> Okay, it should be OK now.
>
> Here's what I've done:
>
>  1. moved one task (for person 3411) from event 371 to event 335
>  2. didn't touch event 335, although some details might be worth
>     preserving from event 371 (reg key, attendance, first contact date)
>  3. removed all tasks that pointed at missing events 371, 382.
>
> Cheers,
> Piotr
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/swcarpentry/amy/issues/332#issuecomment-108480209>.
>

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Comment by pbanaszkiewicz** [comment] 2015-06-03 15:56
> (And I promise never to manually edit the database again.)

We now make almost 200 backups per day (!), we'll be fine :-)

**Closed** 2015-06-03 15:56 UTC
