### ISSUE TITLE
Bulk add persons error

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#1394] opened 2018-11-05 19:56 UTC
Bulk add persons is throwing a Server Error (500).

On the preview screen it looks fine but it returns an error when you click "Verify" or "Confirm and Save"

**Comment by pbanaszkiewicz** [comment] 2018-11-06 19:04
@maneesha with a very short check I was unable to verify this error on current development code. Can you please send me an email with the file you're using for this bulk upload?

**Comment by maneesha** [comment] 2018-11-14 21:01
@shapiromatron   Just sent you an email with the file.  I can't see anything immediately wrong with it.  Othe users have reported this issue as well.

**Comment by pbanaszkiewicz** [comment] 2018-11-14 21:11
@maneesha thanks, I'll look into it tomorrow and see where the error is coming from.

**Comment by shapiromatron** [comment] 2018-11-15 01:56
@maneesha did you mean me? I haven't been active in this project for quite some time...

**Comment by pbanaszkiewicz** [comment] 2018-11-15 18:21
@maneesha the issue is that email address is required, but the "bulk upload" doesn't indicate it strong enough and doesn't correctly verify the incoming data.

For now you can circumvent the error by adding email addresses to your bulk upload data records.

**Comment by maneesha** [comment] 2018-11-15 18:38
I didn't realize email address was required.  I don't remember it being this way.  We don't always have email addresses on our learners (it's not required for a Person) so we can't do that.  Putting in an issue to fix this.

**Comment by maneesha** [comment] 2018-11-15 18:39
@shapiromatron  I have no idea how my typo managed to tag you!  Sorry about that!

**Comment by pbanaszkiewicz** [comment] 2018-11-15 19:10
@maneesha I was wrong, we have people in the database with empty email. I made a hotfix on the server, and I will prepare a solid fix for the `develop` branch (for the next release). Unfortunately the next release already contains too many changes to make a minor release with the hotfix in the meantime.

@maneesha can you please check if the issue is fixed on the server? I tested against the file you sent me and it worked fine.

**Closed** 2018-11-22 19:43 UTC
Labels: priority: essential, type: bug
