### ISSUE TITLE
Update from valid URL causes "Network Connection Error"

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#999] opened 2016-09-06 12:52 UTC
(title says it all)

**Comment by apawlik** [comment] 2016-09-13 21:30
Same here.

![image](https://cloud.githubusercontent.com/assets/2358535/18492148/dd8400ec-7a5d-11e6-9ab9-518efbc25f14.png)

**Comment by narayanaditya95** [comment] 2016-09-13 21:48
FWIW, I haven't been able to reproduce the error on either localhost or amy-dev with the same URL. So, it is a deployment issue.

**Comment by pbanaszkiewicz** [comment] 2016-09-16 19:27
Closing since the error was due to outdated files (see #1003 for details).

**Closed by pbanaszkiewicz** 2016-09-16 19:27 UTC
Labels: bug, deployment, essential
