### ISSUE TITLE
'DC' used to be an option for 'tag' -- disappeared from list?

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#744] opened 2016-04-07 16:07 UTC
See:

![image](https://cloud.githubusercontent.com/assets/829690/14357980/0116bd38-fcb9-11e5-9e59-af8e2d9e3891.png)

**Comment by narayanaditya95** [comment] 2016-04-07 17:03
For what it's worth,
The `DC` tag could have been deleted.
New tags can be added through the admin interface.
`/workshops/admin/workshops/tag/add/` URL adds a new tag.

**Comment by gvwilson** [comment] 2016-04-07 17:03
Deleted by whom??

**Comment by narayanaditya95** [comment] 2016-04-07 17:08
Accidentally deleted from the admin interface by an admin user? That was just a hypothesis.
I cannot think of any other way a tag can be deleted.

@pbanaszkiewicz would answer it better than me.

**Comment by maneesha** [comment] 2016-04-07 17:08
> Deleted by whom??

That's  why I raised this issue.  I know it's easy to add a  tag but it's a problem that it got deleted.  I've never gone into the admin panel.

**Comment by pbanaszkiewicz** [comment] 2016-04-07 17:33
Looking into this issue…

**Comment by gvwilson** [comment] 2016-04-07 17:36
Thanks Piotr.

**Comment by pbanaszkiewicz** [comment] 2016-04-07 17:57
Logs don't show anyone accessing the admin interface in order to remove the tag, which means there's some awful bug in the code that removed the tag.

I'll:
1. bisect the backups to find correct time the removal happened and then check what requests caused it
2. retrieve lost data
3. review our models' on_delete behavior.

It may take me some hours before I'll retrieve the lost data (ie. workshops that were marked DC).

**Comment by pbanaszkiewicz** [comment] 2016-04-07 17:58
@maneesha thank you for reacting this quick, by the way. The lost happened probably in the last 24h.

**Comment by pbanaszkiewicz** [comment] 2016-04-07 19:36
Found the error. It's in the event merge procedure and you can reproduce it by setting base object for merge to object A (ie. `Field` to "Use A"), and strategy for tags to "Use B".

**Comment by gvwilson** [comment] 2016-04-07 19:38
Excellent sleuthing - 
http://www.amazon.com/Heart-Logs-Stream-Processing-Integration/dp/1491909382/ 
for the win.  Please write this one up (both the bug and how you found 
it) when you're done, and bill us for every minute you spend on it.
Thanks,
Greg

**Comment by pbanaszkiewicz** [comment] 2016-04-07 20:07
The data was retrieved.

@gvwilson write up and publish somewhere?

**Comment by gvwilson** [comment] 2016-04-07 20:12
Excellent work.

**Comment by pbanaszkiewicz** [comment] 2016-04-07 20:13
> Excellent work.

And terrible too, because the bug is in code I wrote :-)

**Comment by pbanaszkiewicz** [comment] 2016-04-08 14:50
Forgot to close this issue yesterday :-)

**Closed by pbanaszkiewicz** 2016-04-08 14:50 UTC
Labels: bug, essential
