### ISSUE TITLE
Matching people with trainees

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#1198] opened 2017-06-20 16:34 UTC
When a trainee application is matched to a person, is all the trainee's information supposed to go into the person's record?

See for example this training request:
https://amy.software-carpentry.org/workshops/training_request/665/

was matched to this person:
https://amy.software-carpentry.org/workshops/person/13594/

However the information in the training request does not populate the person's record.  Is there another step to make this happen?

**Comment by chrismedrela** [comment] 2017-07-10 16:45
The trainee's information goes into the person's record only if a new person record is created. If there is already an existing person record in database, it doesn't happen. See [relevant code](https://github.com/swcarpentry/amy/blob/39edaa66203b762d21a4b819e5c58381a821d40d/workshops/views.py#L2846-L2858).

**Comment by pbanaszkiewicz** [comment] 2018-08-11 19:00
Duplicate of #1270, fixed in #1313.

**Closed by pbanaszkiewicz** 2018-08-11 19:00 UTC
Labels: type: question
