### ISSUE TITLE
Badges not showing in the Training profile

### ISSUE THREAD

**Issue by sheraaron** [swcarpentry/amy#1384] opened 2018-10-26 15:45 UTC
Some of the persons who attended this training have been badged, however, none of the badges are showing. I have to click on each learner to see the badge. 

![image](https://user-images.githubusercontent.com/31488403/47577125-2057d300-d914-11e8-8dd8-32f8b5f340f7.png)

**Comment by maneesha** [comment] 2018-10-26 15:49
Closing - duplicate of https://github.com/swcarpentry/amy/issues/1377, being fixed with https://github.com/swcarpentry/amy/pull/1381

**Closed by maneesha** 2018-10-26 15:49 UTC
