### ISSUE TITLE
Problem merging persons with training progress

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#1136] opened 2017-01-17 20:40 UTC
Try merging https://amy.software-carpentry.org/workshops/person/12051/ and https://amy.software-carpentry.org/workshops/person/12839/  

![image](https://cloud.githubusercontent.com/assets/829690/22038955/3cb3f0a2-dccb-11e6-869e-ebf84bc298a2.png)

**Comment by chrismedrela** [comment] 2017-01-18 13:59
@maneesha Please use "combine" for "Training progresses". Let me know if this helped.

**Comment by pbanaszkiewicz** [comment] 2017-01-18 18:28
@maneesha @chrismedrela I'm almost sure that this was fixed in v1.10 - it works on my development server and production database.

**Comment by maneesha** [comment] 2017-01-19 14:39
As of now, I still get this error.  
"Training progress" is not an option in all the fields you can merge.

**Comment by pbanaszkiewicz** [comment] 2017-01-21 13:41
@maneesha I'm pretty sure this will be fixed when we release v1.10.

**Comment by chrismedrela** [comment] 2017-01-21 14:24
@maneesha, yes that was fixed in #1118. I'm closing it as it's a duplicate of #1117.

**Closed by chrismedrela** 2017-01-21 14:24 UTC
Labels: bug
