### ISSUE TITLE
User profile should show list of workshops

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#1192] opened 2017-06-06 20:19 UTC
When a regular user logs in to view/edit their own profile they should also be able to view a list of workshops they've participated in & the role at each.  

They should not be able to edit this list.

**Comment by pbanaszkiewicz** [comment] 2018-08-11 18:55
Duplicate of #1263, resolved in #1269.

**Closed by pbanaszkiewicz** 2018-08-11 18:55 UTC
Labels: type: enhancement
