### ISSUE TITLE
Change your own permission

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/amy#1199] opened 2017-06-23 12:45 UTC
Looks like you can change your own permissions, include giving you superuser permission.

**Comment by maneesha** [comment] 2017-06-23 12:55
Emailed @pbanaszkiewicz @chrismedrela @narayanaditya95  as this is an urgent fix.

**Comment by pbanaszkiewicz** [comment] 2017-06-23 14:24
This view is accessible by people who are superusers or belong to any of the groups: administrator, steering committee, invoicing, trainers. All these people are considered admins in AMY and therefore are able to change other people's permissions.

**Comment by maneesha** [comment] 2017-06-24 16:57
OK.  To be clear, regular users (who log in just to view/edit their own profiles) can not do this -- correct?

**Comment by chrismedrela** [comment] 2017-06-24 18:27
> OK. To be clear, regular users (who log in just to view/edit their own profiles) can not do this -- correct?

Yes, they can't -- they don't have even access to the person edit view.

**Comment by rgaiacs** [comment] 2017-06-26 15:33
> This view is accessible by people who are superusers or belong to any of the groups: administrators, steering committee, invoicing, trainers.

But non-administrators trainers can self-assign administrators.

**Comment by chrismedrela** [comment] 2017-07-10 16:58
@rgaiacs I tried to reproduce it, but I cannot. If a person doesn't belong to `administrators` group and is not a superuser, then "change permissions" button is disabled and you cannot change your own or sb's else permissions. Could you provide me specific instructions how to reproduce it?

**Comment by pbanaszkiewicz** [comment] 2018-06-17 17:50
Closing because it's not possible to change permissions by non-admin user. Additionally, a user considered admin needs to have `change Person` permission.

**Closed by pbanaszkiewicz** 2018-06-17 17:50 UTC
Labels: priority: essential, status: needs feedback
