### ISSUE TITLE
Matched Training and Request Training Profile Merge

### ISSUE THREAD

**Issue by sheraaron** [swcarpentry/amy#1270] opened 2018-06-05 17:17 UTC
If a person already has a profile in AMY and I do the Matched Training option, they do not merge. The profile on record trumps the "Request Training" profile. In order for me to not lose any information, I must create a new account and then go back and merge the two accounts. 

See this example: He already has a profile, but if you go to Requested Trainings and type his name, he has a more detailed record. 

see person https://amy.software-carpentry.org/workshops/person/16165/
and training request https://amy.software-carpentry.org/workshops/training_request/1692/

**Comment by maneesha** [comment] 2018-07-16 12:45
Bumping this up @pbanaszkiewicz  can we get this fixed in the next release?

**Comment by pbanaszkiewicz** [comment] 2018-07-16 14:51
@maneesha scheduling for the next release as requested.

**Comment by pbanaszkiewicz** [comment] 2018-07-17 18:02
@maneesha and @sheraaron, this issue is deeper than I originally thought. In general, matching a training request was intended to not change any person. If there's no matching person, a new one is created from request information.

We can update user profile automatically when matching, but deciding which information is more accurate (e.g. profile's occupation vs request's occupation) is hard.

Right now I don't have any concrete idea how to fix this issue.

According to the source code, only these information are overwritten in case "Match" is used:
1. may contact = True
2. is active = True
3. social logging is synchronized

When using "Create", a new person profile has these fields filled up:
1. username, personal, middle, family, email,
2. github
3. affiliation
4. knowledge domains
5. occupation

Please let me know how you want me to fix this issue.

**Comment by maneesha** [comment] 2018-07-23 15:00
Actually @pbanaszkiewicz  is it possible to do something like we do for merge events or merge persons - where we choose what to keep?

**Comment by pbanaszkiewicz** [comment] 2018-07-24 15:52
@maneesha yes, it's possible, but there isn't much overlap between these models:

Person | TrainingRequest
---------- | -----------
*nothing* | person
*nothing* | group name
**personal** | **personal**
**middle** | **middle**
**family** | **family**
**email** | **email**
gender | *nothing*
may contact | *nothing*
publish profile | *nothing*
**country** | **country**
airport | *nothing*
**github** | **github**
twitter | *nothing*
url | *nothing*
user notes | *nothing*
**notes** | **notes**
**occupation** | **occupation**, occupation other
**affiliation** | **affiliation**
badges | *nothing*
lessons | *nothing*
*nothing* | location
**country** | **country** (repeated)
*nothing* | underresourced
**domains** | **domains**, domains other
*nothing* | underrepresented
*nothing* | nonprofit teaching exp.
*nothing* | previous involvement
*nothing* | previous training, previous training other, previous training explanation
*nothing* | previous teaching exp., previous teaching exp. other, previous teaching exp. explanation
*nothing* | programming language usage frequency
*nothing* | teaching freq. expectation, teaching freq. expectation other
*nothing* | max travelling frequency, max travelling freq. other
*nothing* | reason
*nothing* | comment
data privacy agreement | data privacy agreement
*nothing* | workshop teaching, training completion agreements, CoC agreement
notes | notes (repeated)
is active | *nothing*
**occupation** (repeated) | **occupation**
orcid | *nothing*

**Comment by pbanaszkiewicz** [comment] 2018-07-24 18:17
@sheraaron @maneesha just to be clear, do also want an interface similar to matching persons or matching events? Or just simply overwrite all possible Person's fields with TrainingRequest's fields?

**Comment by sheraaron** [comment] 2018-07-24 18:58
@pbanaszkiewicz  You can simply overwite all possible Person's fields with TrainingRequest's fields. 

Thanks!

**Closed** 2018-07-31 18:41 UTC
Labels: component: user interface (UI), type: enhancement
