### ISSUE TITLE
Have separate columns for person and email in display of badges

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#315] opened 2015-05-28 02:10 UTC
The person field should link to the person's individual record; the email address should be a mailto.

**Comment by wking** [comment] 2015-05-28 02:59
On Wed, May 27, 2015 at 07:10:14PM -0700, Greg Wilson wrote:
> The person field should link to the person's individual record; the
> email address should be a mailto.

Duplicate of #312?  Or is this just building on #312 by splitting the
name and email into separate columns?

**Comment by gvwilson** [comment] 2015-05-28 10:09
Made the same note for tasks and badges; I'll probably find other places 
where we should make the same change as well.  Or create a snippet that 
takes a `person` and produces `<td>{{ person.get_full_name}}</td><td>{{ 
person.email }}</td>` with appropriate wrappers to create the hyperlink 
and mailto.

**Closed** 2015-06-03 17:55 UTC
Labels: enhancement
